// <auto-generated />
using System;
using CsgoAntiCheatDudu;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsgoAntiCheatDudu.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220415205356_dropBoxToken")]
    partial class dropBoxToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Common.Player", b =>
                {
                    b.Property<string>("SteamId")
                        .HasColumnType("varchar(95)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAntiCheatOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastPhotoTaken")
                        .HasColumnType("datetime");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SteamId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Common.ServerStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServerStatus", (string)null);
                });

            modelBuilder.Entity("Common.TokenDropbox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DropboxTokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
